services:
  - type: web
    name: skedu-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn skedu.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: skedu-db
          property: connectionString

databases:
  - name: skedu-db
    databaseName: newedu
    user: root
